options:
     logging: CLOUD_LOGGING_ONLY 
steps:

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', 'app.yaml', '--quiet']

substitutions:
  _ZONE: asia-south2